### ISSUE TITLE
** ATTENTION ** 

### ISSUE THREAD

**Issue by davewatson91** [lewisbenge/hass-amber-electric#25]
I have been in contact with Amber -> this API will be deprecated over a 6 month period, with a new API almost ready for release. One of the developers at Amber (creating the API, will also be developing (in his personal capacity I believe) an integration for Home Assistant.

**Comment by bengAThome** [comment]
Interesting development!

**Comment by micarex** [comment]
I was in contact with them last week as well.  I noticed that during the recent price spikes in my area that the API was returning drastically different results to the app.  They confirmed that they have done a lot of recent work on the pricing in the app but haven't updated the API accordingly.   They then confirmed they are working on a new API but they didn't say one of their devs was going to develop the HA plugin, so that's good news.

**Comment by davewatson91** [comment]
> at they have done a lot of recent work on the pricing in the app but haven't updated the API accordingly. They then confirmed they are workin

Have noticed the same - we've had some horrible spikes of recent - almost enough to question our change from our previous provider.... Having the API working would certainly help us with mitigating some costs, but it's hard to mitigate with hours of $1+ spikes per evening. 

I suspect maybe he's not advertising it too much, as I suspect it will not be an official Amber integration? Hopefully it won't take too long until we see it up and running!

**Comment by bengAThome** [comment]
Yeah these spikes have been challenging, I was thinking the same that it
might be better to go back to single tariff.
However the average still seems to be working out.
I hope whoever at Amber that does the Dev work engages with us though, and
does not just do it on their own...

**Comment by madpilot** [comment]
I'm the Amber Dev 👋

**Comment by madpilot** [comment]
> I suspect maybe he's not advertising it too much, as I suspect it will not be an official Amber integration?

Once I've got something that I can start showing you all, I will. The plan is to have it part of Home Assistant core, rather than a custom component, but to start with a custom component makes the most sense, but that won't happen until we finish the API work, which is close, but we are a small team, and my attention is diverted on almost a daily basis.

Big ups to @lewisbenge for getting this component out! I'm using his integration at the moment too. I've been controlling my ducted air conditioning based on network prices (using the same wrong API as all of you - I can't even get access to it remotely yet, and I'm the one writing it!) - it's definitely helped me make a business case for this work.

**Comment by bengAThome** [comment]
Great to hear Myles!
I agree, the current API isn't perfect, but I am manually using it as a
check before using power hungry devices, like dryers etc
I'm working on using RGB LEDs to provide a traffic light style indication
near all these devices, with a bit of extra intelligence.
Eg green for cheap etc, but also have them animate the direction. Eg green
going Amber red to indicate the price direction is heading up.

The second piece of the puzzle is to get real-time power usage. (Currently
using Powerpal) but want to get it automatic too.

**Comment by madpilot** [comment]
The new API will have 24-hour delayed usage, but we don't have access to real-time at the moment. For reactive real-time (ie, how much power are you using this instant) Powerpal or Eagle 200 (or similar) or getting a battery with an API are your best bet

**Comment by davewatson91** [comment]
> The new API will have 24-hour delayed usage, but we don't have access to real-time at the moment. For reactive real-time (ie, how much power are you using this instant) Powerpal or Eagle 200 (or similar) or getting a battery with an API are your best bet

I've actually just setup ESPHome on an ESP32 to use the [CircuitSetup board](https://circuitsetup.us/product/expandable-6-channel-esp32-energy-meter/). I have to admit that this is the best bit of energy monitoring that I've ever used - its accurate, configurable and running ESPHome make it super easy. I will be interested to pull the stats in, but the 24hr delay is still OK for that, so long as the real time pricing is spot on :)

Let us know if you need any help in getting the component off the ground (or working for core)- it is definitely super valuable (I'm switching A/C, Hot Tub & Hot Water Service currently, which combined can avoid inadvertently using 14kWh)

**Comment by madpilot** [comment]
> ESPHome on an ESP32 to use the CircuitSetup board.

Nice! I'm investigating using Zigbee to talk to my smart meter, as it's non-intrusive. However, my meter is quite far from my house and has (ironically) no power, so the Eagle 200 won't work. I'm looking at homebrewing something, possibly solar powered.

**Comment by bengAThome** [comment]
That's a nice board! Definitely an option once I can afford it :)
Powerpal us a great device, but no API.
The 24hr delay is fine for me too.
It's the spot price that I'd like to be 💯 accurate.

**Comment by davewatson91** [comment]
> > ESPHome on an ESP32 to use the CircuitSetup board.
> 
> Nice! I'm investigating using Zigbee to talk to my smart meter, as it's non-intrusive. However, my meter is quite far from my house and has (ironically) no power, so the Eagle 200 won't work. I'm looking at homebrewing something, possibly solar powered.

Unfortunately the smart meter I have doesn't have the Zigbee option, only GSM from what I could dig up :( That was ultimately my first goal. The beauty of the CircuitSetup board is that I can manage individual circuits, and take into account power factor, reverse current and such. Example of how I'm currently setup (although not my final intent, just the quick and dirty to get up and running). I've got rules setup to run things when I'm exporting power and such. 

![image](https://user-images.githubusercontent.com/51277302/120408498-80e40200-c392-11eb-8fb2-1e24158f6e1b.png)

**Comment by bengAThome** [comment]
That looks 1000 times better than my dashboard lol.

**Comment by madpilot** [comment]
How is everyone writing their automations? YAML, UI, NodeRed, Appdaemon, other?

**Comment by davewatson91** [comment]
I migrated to NodeRed about 6 months back, and surprisingly haven't looked back. Running HA / NodeRed in Docker (amongst 20 other containers).

**Comment by bengAThome** [comment]
Mixture some Yaml, some node-red.
Plus use grafana for those sweet graphs :)

**Comment by micarex** [comment]
> How is everyone writing their automations? YAML, UI, NodeRed, Appdaemon, other?

I'm currently using the UI for my automations but I'm in the process of adding AppDaemon because I need to execute more complex logic than what the HASS automations allow.  I also need to send REST APIs calls with Digest authentication to my Fronius inverter from a script and as best I can tell, there's nothing in HASS that can do this at the moment.  

I'm switching hot water heating, reverse cycle aircon, wireless GPOs (Ikea Tradfri) and wired GPOs (NetIO), and charging battery from grid when Amber price is low and discharging when price is high.  The built in automations do a good job for simple tasks and I'll keep them going, but I need to start writing custom Python to add more complex stuff.   I'm also doing my more complex graphing & analysis in InfluxDB 2. 

Example InfluxDB 2 
![image](https://user-images.githubusercontent.com/26860101/126029538-e3cf29e6-8759-4c7d-8708-58f975bf2a1a.png)

Example HASS Dashboard
![image](https://user-images.githubusercontent.com/26860101/120909391-03810000-c6b8-11eb-96c5-65f5de5b89c8.png)

**Comment by davewatson91** [comment]
@micarex intrigued as to how you're controlling the flow to/from the grid? 

Why the appdaemon vice something like NodeRed?

**Comment by micarex** [comment]
> @micarex intrigued as to how you're controlling the flow to/from the grid?
> 
> Why the appdaemon vice something like NodeRed?

I probably could use node red and write my complex logic in js.  However I've already written quite a lot of python code to do what I want.  I wrote it before I discovered HASS so I figure it is easier for me to keep going with python.  I'm in the process of writing a trading algorihtm which detects the best price ranges during the day to buy and sell energy and then I need to control the relays to turn devices on/off based on those time periods.   So far I've been using somewhat fixed values (e.g. If Amber feed is price is greater than 15c then discharge battery to grid, but I'm now moving to more sophisticated approach of figuring out the optimum time based on forecast prices.  Also determining whether to discharge/charge battery is also heavily influenced by other variables such as time of day and battery SOC.  e.g. No point discharging battery and exhausting battery energy at 5 p.m. at 15c feed in if I am only going to have to buy it back at 6-7 pm at 30c to cater for evening energy usage.). 

As for grid flow, at the moment it is fairly simple (in logic) right now which is why I want to improve it.

It have a set of HASS automations which are triggered based on the Amber pricing.
![image](https://user-images.githubusercontent.com/26860101/120909813-55c42000-c6bc-11eb-83cc-0543bdaebca3.png)

Based on thresshold values I then run scripts to send MODBUS commands to my Fronius inverter to tell the battery to charge/discharge.

![image](https://user-images.githubusercontent.com/26860101/120909827-915eea00-c6bc-11eb-8017-a0df3dbf7755.png)

But I'd like to improve these to charge at a calculated percentage rate depending on forecast pricess too.

**Comment by micarex** [comment]
I found that one of the unintended consequences of setting the battery to discharge to grid is that the Fronius inverter then turns on my hot water and aircon relays at the wrong time because the smart meter tells the Fronius that there is excess energy flowing to the grid and under normal circumstances this means I have excess solar going to the grid so I want to consume the energy via hot water heating and running aircon (heating) rather than getting paid a pittance to send it to the grid.  However the so called 'smart meter' has no idea why energy is flowing to the grid.  So when the battery is discharging to the grid I need to turn off the Fronius relay automations to stop it consuming the energy I am deliberately trying to send to the grid when Amber price is high.  This requires me to send a REST API call using digest authentication to the Fronius Inverter.

**Comment by davewatson91** [comment]
So they're the same logic pains that I'm running through now. Balancing it with trying to make sure that the hot-tub and hot water service get enough periods of running throughout the day to stay hot, while trying to optimise using the cheapest prices.. 

What sort of battery storage are you running with the fronius? I've been tossing up with this as the next logical step.... 

The direction of flow has also been something I've been working on. Turns out that the smart meters are useless for it, but the  power monitor I mentioned above does handle current flow direction - has helped with that same problem.

**Comment by davewatson91** [comment]
What model Fronius are you running?

**Comment by micarex** [comment]
> What model Fronius are you running?

I have two.  A Primo 4.0kw and I also have a Primo Gen24 6.0kw hybrid inverter.  I am on the beta program for the Gen24 and the largest model they make is 6.0kw at the moment, so I had to get the Primo 4.0 to make a 10kw system (with 12.54kw of panels).  I use the Gen24 for all the smart stuff because it has much more advanced power control.  Having said that, most of the stuff I'm doing can also be done with the Primo (or the 3 phase Symo).

**Comment by micarex** [comment]
Refer https://www.mcelectrical.com.au/wp-content/uploads/2017/02/Fronius_Feature.x29689.pdf page 5 for the basic concept.  The Fronius inverters have 4 inbuilt 12v relays that can be use to control contactors to switch 240v loads.

**Comment by micarex** [comment]
I am using a [BYD Battery Box HVM 11.04kwh](https://bydbatterybox.com/uploads/downloads/BYD%20Battery-Box%20Premium_Datasheet_HV-AU%20V1.2%20EN-5eec6422498ad.pdf) battery.  This is the Fronius recommended battery for use with the Gen24 inverters now that they don't produce batteries themselves.

**Comment by micarex** [comment]
Can you elaborate on the direciton of flow issue.  I can tell direction of flow using my Fronius Smart meter.  Power values are negative or positive depending on direction of flow.  Refer Power Grid guage in the screen shot I posted.  It shows +1016.88w where one I have taken just now shows negative.

![image](https://user-images.githubusercontent.com/26860101/120918875-1a484680-c6fa-11eb-958a-553064a8f43d.png)

**Comment by davewatson91** [comment]
Yeah ok - so that's the same, and you have the same generation stats - why not roll those metrics as a conditional check into the automations for the relays? (i.e. if producing x watts, don't turn off, or if feed in tarrif is high, don't turn on, to maximise production).

**Comment by micarex** [comment]
> Yeah ok - so that's the same, and you have the same generation stats - why not roll those metrics as a conditional check into the automations for the relays? (i.e. if producing x watts, don't turn off, or if feed in tarrif is high, don't turn on, to maximise production).

I'm already doing some checks of metrics in the HA automations, but there's a more fundamental limitation that I came across.

The problem is that the Fronius relay setting are not that sophisticated.  And HASS can't actually control the relays directly because there is no published REST API or MODBUS commands to control the relays.   You just set the values in the UI.  e.g.

![image](https://user-images.githubusercontent.com/26860101/120919115-4b754680-c6fb-11eb-8175-9f9b11c00f0b.png)

So my automations are currently split between HA and the Fronius inverter.  The Fronius does hot water diversion and reverse cycle aircon, and I'm using HA for battery charge/discharge and GPOs. 

My next step is to get HA to control the lot so that they all work in harmony.  I had to figure out a way for HA to control the relays.  This bit was very tricky.  Since there is not official interface on the inverter to make this happen, I ended up sniffing the network traffic with wireshark between the UI and the inverter.  Turns out there is a set of internal APIs and JSON values that I have learned to mimick.  Using this method I can control the configuration of the relays (on/off and thressholds) programmatically.  However the Fronius requires digest authentication for the internal APIs to work.  I have a few hundreds lines of python to do the digest auth and construct the appropriate API calls.  I successfully got this running via AppDaemon a couple of weeks ago.  

So that was a long answer to your question, but now I should now be able to automate the lot from HA dynamically setting the relays settings on the Fronius.  And I can incorporate whatever other conditions and variables into the mix as you've suggested.

**Comment by davewatson91** [comment]
yeah wow - I missed the fundamental piece about the relays not being externally controllable. 

I will be bookmarking this, after reading up on the fronius, it looks like it may fit the bill for what I need..... 

Thanks!

**Comment by bengAThome** [comment]
Just curious, how will you go with the remote power grid control?
Where they will turn off your export if the grid gets unstable.

**Comment by micarex** [comment]
> Just curious, how will you go with the remote power grid control? Where they will turn off your export if the grid gets unstable.

Thankfully this doesn't happen in Vic yet.  But if it does get introduced the Fronius Gen24 inverter supports it via the built in Demand Response Modes.  I haven't thought much about it, but I would likely compare the PV production against the amount going to the grid and ramp up my consumption based on whatever the grid refuses to take.  I might be able to read the DRM modes via MODBUS as well to make this easier, but I haven't checked.

**Comment by gorillica** [comment]
@davewatson91, how did you set up your Lovelace dashboard, particularly the graph of price prediction? I've been wracking my brains over that!

Glad to hear that there’s the prospect of progress with the new API, @madpilot! I'm only a new Amber customer (haven't even had a smart meter installed yet), but am looking forward to getting automations in Node-Red to turn off high-draw devices (ACs, floor heating, perhaps even dishwasher/washing machine to prevent them being turned on during price-spikes…).

**Comment by davewatson91** [comment]
It's certainly not mine! - Credit comes from here: https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/48

My lovelace code below: 

```
type: custom:apexcharts-card
graph_span: 48h
header:
  show: true
  title: Amber Price Prediction (General Usage - E1)
span:
  start: hour
  offset: '-24h'
apex_config:
  chart:
    type: area
    height: 300
  stroke:
    show: true
    width: 2
    curve: smooth
  legend:
    show: false
  dataLabels:
    enabled: false
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        month: ddd
        day: ddd
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 20
        - 100
        - 100
        - 100
series:
  - entity: sensor.amber_general_usage_price
    name: Predicted Price
    type: area
    extend_to_end: false
    data_generator: |
      return entity.attributes.price_forcecast.map((entry) => {
        return [new Date(entry.pricing_period), entry.price];
      });
  - entity: sensor.amber_general_usage_price
    name: Historic Price
    type: area
    extend_to_end: false
````

```
type: custom:apexcharts-card
graph_span: 59h
header:
  show: true
  title: Amber Price Prediction (Solar Feed-In)
span:
  start: hour
  offset: '-1d'
apex_config:
  chart:
    type: area
    height: 300
  stroke:
    show: true
    width: 3
    curve: smooth
  legend:
    show: false
  dataLabels:
    enabled: false
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        month: ddd
        day: ddd
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: true
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 20
        - 100
        - 100
        - 100
series:
  - entity: sensor.amber_solar_feed_in_tariff
    name: Predicted Price
    type: area
    extend_to_end: false
    data_generator: |
      return entity.attributes.price_forcecast.map((entry) => {
        return [new Date(entry.pricing_period), entry.price];
      });
  - entity: sensor.amber_solar_feed_in_tariff
    name: Historic Price
    type: area
    extend_to_end: false
```

**Comment by bacco007** [comment]
That's my setup! :)

I hope it still works I haven't had a chance to look at it recently

**Comment by davewatson91** [comment]
> That's my setup! :)
> 
> I hope it still works I haven't had a chance to look at it recently

Thanks for sharing originally - certainly working for me still!

**Comment by gorillica** [comment]
Thanks, @davewatson91 and @bacco007! That's really helpful. I've been meaning to try the Apex Charts card, but have been a bit daunted. I've got the historic data showing now, but will need to fiddle, as your data generator for the forecasts doesn't seem to be working for me on first try…

**Comment by J-Lich** [comment]
Thanks @bacco007! Still using your setup also. works well.
Keen to see this new API and what it brings!

![Screenshot_2021-06-12 13 32 46_5vGP16](https://user-images.githubusercontent.com/13187191/121764457-3711cd80-cb83-11eb-97b7-0ca8a9b17fe7.png)

**Comment by chiefcomm** [comment]
Hi @davewatson91 I'm interested in the [CircuitSetup board](https://circuitsetup.us/product/expandable-6-channel-esp32-energy-meter/).   Did you source locally or from the US?   Ultimately what power supply did you go with as I do not want to blow mine apart when it arrives :-)  I should add I'm in Australia therefore need a AU power supply...

**Comment by davewatson91** [comment]
> Hi @davewatson91 I'm interested in the [CircuitSetup board](https://circuitsetup.us/product/expandable-6-channel-esp32-energy-meter/). Did you source locally or from the US? Ultimately what power supply did you go with as I do not want to blow mine apart when it arrives :-) I should add I'm in Australia therefore need a AU power supply...

Sourced straight from the US.. Shipping was quite painful, and got held up in customs for a fortnight in Aus. 

Power supply was a [nice easy one from Jaycar](https://www.jaycar.com.au/9vac-1a-unregulated-power-supply-7dc-plugs/p/MP3027) - worked a treat. Running ESPHome on mine, and doing the rest in Home Assistant.

**Comment by adampetrovic** [comment]
Is this the new API we're looking for? cc @madpilot 

https://app.amber.com.au/developers/

**Comment by madpilot** [comment]
Yup.

I should have a new HA component in the next day or two. Unfortunately the Python OpenAPI generator did a hatchet job, so I needed to build the interface manually

**Comment by davewatson91** [comment]
> Yup.
> 
> I should have a new HA component in the next day or two.

Wow, super impressed with your turnaround. Looking forward to it! 

Thankyou very much!

**Comment by chiefcomm** [comment]
> Yup.
> 
> I should have a new HA component in the next day or two.

Legend love your work, can't wait to start using it.
Thanks

**Comment by madpilot** [comment]
Here's a really early cut: https://github.com/madpilot/hass-amber-electric

![image](https://user-images.githubusercontent.com/19585/122875279-6391ca80-d377-11eb-8ff2-454c2a8099d0.png)

It's not really well tested yet, but i you are feeling lucky, install it and start giving me feedback (on the other repo).

If you aren't a dev, this may very well break, so maybe wait until it's a little more stable... 😄

**Comment by davewatson91** [comment]
About to have a play. 
Looks like issues aren't open on your new repo. 

Also because you forked it from the other one, I can't work out how to fork it again (since this is already a fork) - wanted to update the API url on the instructions (url should be https://app.amber.com.au/developers/ I believe)

**Comment by madpilot** [comment]
Just turned them on

**Comment by bengAThome** [comment]
Fantastic news! I'm not able to test it for a couple if weeks but will
definitely give it a shot as soon as I can.

**Comment by mikemortimer** [comment]
@madpilot 🙏  awesome work! working really really well

**Comment by bacco007** [comment]
Bugger - looks like I cant move across, was tracking the cost to see how it aligned with our usage before committing - now you need an account to log in.

Good work though!  Good to see it get some support

**Comment by chiefcomm** [comment]
@madpilot this is terrific, love your work.
![image](https://user-images.githubusercontent.com/45157523/123066102-1aaf4400-d453-11eb-96ad-76f66493188a.png)

**Comment by davewatson91** [comment]
> @madpilot this is terrific, love your work.
> ![image](https://user-images.githubusercontent.com/45157523/123066102-1aaf4400-d453-11eb-96ad-76f66493188a.png)

@chiefcomm how did you handle the time zones in your data_generator for the forecast chart?

**Comment by chiefcomm** [comment]
> @chiefcomm how did you handle the time zones in your data_generator for the forecast chart?

@davewatson91 I used "nem_date" as the time it seemed to work OK, as the UTC times aren't working correctly as per your issue #11 Time Zones.

            data_generator: |
              return entity.attributes.forecasts.map((entry) => {
                return [new Date(entry.nem_date), entry.per_kwh];
              });

**Comment by davewatson91** [comment]
> > @chiefcomm how did you handle the time zones in your data_generator for the forecast chart?
> 
> @davewatson91 I used "nem_date" as the time it seemed to work OK, as the UTC times aren't working correctly as per your issue #11 Time Zones.
> 
> ```
>         data_generator: |
>           return entity.attributes.forecasts.map((entry) => {
>             return [new Date(entry.nem_date), entry.per_kwh];
>           });
> ```

Exactly how I did it - thought you may have had a different solution. Thanks! 

Some related [discussion here](https://github.com/madpilot/hass-amber-electric/issues/11) for timezone explanations.

**Comment by madpilot** [comment]
FYI There was a bug in the startTime and endTime field, they were set to UTC-10, rather than UTC.

It's fixed now, which I suspect will fix whatever the subtext of your previous comment is @davewatson91  😆

@chiefcomm I assume you are basing those times off the newTime field? If so, all good (note: NEW time is always UTC+10: no daylight savings). If you are using the start_date, things might shift 10 hours once this fix hits prod.

**Comment by madpilot** [comment]
Ah, I see you all worked that out yourselves. Point is - start and end dates are now in the correct UTC

**Comment by davewatson91** [comment]
> Ah, I see you all worked that out yourselves. Point is - start and end dates are now in the correct UTC

Thanks - you're a gun @madpilot

**Comment by micarex** [comment]
Awesome work @madpilot .  I've converted over to the new API and all is working well.  My automations will be much happier now with the more accurate price.

Does anybody have a way to show the forecast prices for future intervals in a card in the HA UI?  Similar to what we see on the Amber site?

**Comment by madpilot** [comment]
I'm planning on doing a custom card, but that might be awhile, as it's the bottom of my todo list 😉

**Comment by micarex** [comment]
@madpilot , I also have a feature suggestion for next version if you are continuing to develop it.  It would be good to have variables for the future forecast periods which represent the highest and lowest forecast values.  These can then be used in Automations to understand whether the current price and forecast price are higher or lower than the values in the subsequent forecast periods.  So by way of example, if the current and forecast prices are:
12 (current), 15 (forecast), 18 (forecast+1), 29 (forecast+2), 38 (forecast+3), 24 (forecast+4), 17 (forecast+5), 12 (forecast+6), 8 (forecast+7)
Then the values would be:
feed_in_price=12 (already in current version)
feed_in_forecast=15 (already in current version)
feed_in_forecast_highest=38 (new feature suggestion)
feed_in_forecast_lowest=8 (new feature suggestion)

Another useful value would be the number of increasing or decreasing forecast values before the price turns the opposite direction.  So in the example above:
feed_in_forecast_increasing_intervals=3   (15, 18, 29 before hitting highest value of 38.  Zero if already at highest)

**Comment by micarex** [comment]
> > @madpilot this is terrific, love your work.
> > ![image](https://user-images.githubusercontent.com/45157523/123066102-1aaf4400-d453-11eb-96ad-76f66493188a.png)
> 
> @chiefcomm how did you handle the time zones in your data_generator for the forecast chart?

Just realised you might have already done what I was looking for @chiefcomm.  How did you add the predicted values to the graph card, and which graph card are you using to do that?  That's an great visual.

**Comment by madpilot** [comment]
Yeah, I had rough plans for something similar, as well as min and max rolling windows, ie time until cheapest 2 hour window, time until the most expensive 4 hour window, which should simplify some prediction stuff for starting long running devices like dishwashers or dryers.

**Comment by micarex** [comment]
> Yeah, I had rough plans for something similar, as well as min and max rolling windows, ie time until cheapest 2 hour window, time until the most expensive 4 hour window, which should simplify some prediction stuff for starting long running devices like dishwashers or dryers.

Yes that would indeed be really useful.

**Comment by chiefcomm** [comment]
> > > @madpilot this is terrific, love your work.
> > > ![image](https://user-images.githubusercontent.com/45157523/123531878-96f3a100-d74b-11eb-9298-583c4cf03c50.png)
> > 
> > 
> > @chiefcomm how did you handle the time zones in your data_generator for the forecast chart?
> 
> Just realised you might have already done what I was looking for @chiefcomm. How did you add the predicted values to the graph card, and which graph card are you using to do that? That's an great visual.

I'm using Apex Charts https://github.com/RomRider/apexcharts-card configuration is below.

### Start of Apex Chart Configuration
      - type: custom:apexcharts-card
        graph_span: 30h
        header:
          show: true
          title: "Amber Price 24hrs"
          show_states: true
          colorize_states: true
        now:
          show: true
          color: red
          label: Now
        span:
          start: minute
          offset: -24h
        apex_config:
          chart: { type: "area", height: 250 }
          stroke: { show: true, width: 2, curve: smooth }
          legend: { show: false }
          dataLabels: { enabled: false }
          xaxis:
            {
              type: "datetime",
              labels: { datetimeFormatter: { month: "ddd", day: "ddd" } },
            }
          fill:
            {
              type: "gradient",
              gradient:
                {
                  shadeIntensity: 1,
                  inverseColors: false,
                  opacityFrom: 0.45,
                  opacityTo: 0.05,
                  stops: [20, 100, 100, 100],
                },
            }
        series:
          - entity: sensor.2115_general_price
            name: Current Price
            curve: smooth
            type: area
            color: cyan
            extend_to_end: false
          - entity: sensor.2115_renewables
            name: Renewables in Grid
            curve: smooth
            type: area
            color: white
            extend_to_end: false
            show:
              in_header: true
              in_chart: true
          - entity: sensor.2115_general_forecast
            name: Renewables in Grid
            curve: smooth
            type: area
            color: white
            extend_to_end: false
            show:
              in_header: false
              in_chart: true
            data_generator: |
              return entity.attributes.forecasts.map((entry) => {
                return [new Date(entry.start_time), entry.renewables];
              });
          - entity: sensor.2115_general_forecast
            name: Predicted Price
            type: area
            color: orange
            extend_to_end: false
            show:
              in_header: true
              in_chart: false
          - entity: sensor.2115_general_forecast
            name: Predicted Price
            type: area
            color: orange
            extend_to_end: false
            show:
              in_header: false
              in_chart: true
            data_generator: |
              return entity.attributes.forecasts.map((entry) => {
                return [new Date(entry.start_time), entry.per_kwh];
              });
### End of Apex Chart Configuration

**Comment by adampetrovic** [comment]
The above configuration updated to use the new integration by @madpilot 

```yaml
type: custom:apexcharts-card
graph_span: 24h
now:
  show: true
  color: red
  label: now
header:
  show: true
  show_states: true
  colorize_states: true
  title: Amber Price Prediction (General)
span:
  start: minute
  offset: '-16h'
apex_config:
  chart:
    type: area
    height: 300
  stroke:
    show: true
    width: 2
    curve: smooth
  legend:
    show: false
  dataLabels:
    enabled: false
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        month: ddd
        day: ddd
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 20
        - 100
        - 100
        - 100
series:
  - entity: sensor.amber_general_price
    name: Historic Price
    type: area
    extend_to_end: false
  - entity: sensor.amber_general_forecast
    name: Predicted Price
    type: area
    color: orange
    extend_to_end: false
    data_generator: |
      return entity.attributes.forecasts.map((entry) => {
        return [new Date(entry.nem_date), entry.per_kwh];
      });
```

**Comment by chiefcomm** [comment]
> > > @madpilot this is terrific, love your work.
> > > ![image](https://user-images.githubusercontent.com/45157523/123532002-9f001080-d74c-11eb-90b6-47653349b896.png)
> > 
> > 
> > @chiefcomm how did you handle the time zones in your data_generator for the forecast chart?
> 
> Just realised you might have already done what I was looking for @chiefcomm. How did you add the predicted values to the graph card, and which graph card are you using to do that? That's an great visual.

@micarex I'm using Apex Charts https://github.com/RomRider/apexcharts-card configuration below.  I use start_time as opposed to nem_date also ignore the times as my PC is set to France Time.

      ### Start of Apex Chart Configuration
      - type: custom:apexcharts-card
        graph_span: 30h
        header:
          show: true
          title: "Amber Price 24hrs"
          show_states: true
          colorize_states: true
        now:
          show: true
          color: red
          label: Now
        span:
          start: minute
          offset: -24h
        apex_config:
          chart: { type: "area", height: 250 }
          stroke: { show: true, width: 2, curve: smooth }
          legend: { show: false }
          dataLabels: { enabled: false }
          xaxis:
            {
              type: "datetime",
              labels: { datetimeFormatter: { month: "ddd", day: "ddd" } },
            }
          fill:
            {
              type: "gradient",
              gradient:
                {
                  shadeIntensity: 1,
                  inverseColors: false,
                  opacityFrom: 0.45,
                  opacityTo: 0.05,
                  stops: [20, 100, 100, 100],
                },
            }
        series:
          - entity: sensor.2115_general_price
            name: Current Price
            curve: smooth
            type: area
            color: cyan
            extend_to_end: false
          - entity: sensor.2115_renewables
            name: Renewables in Grid
            curve: smooth
            type: area
            color: white
            extend_to_end: false
            show:
              in_header: true
              in_chart: true
          - entity: sensor.2115_general_forecast
            name: Renewables in Grid
            curve: smooth
            type: area
            color: white
            extend_to_end: false
            show:
              in_header: false
              in_chart: true
            data_generator: |
              return entity.attributes.forecasts.map((entry) => {
                return [new Date(entry.start_time), entry.renewables];
              });
          - entity: sensor.2115_general_forecast
            name: Predicted Price
            type: area
            color: orange
            extend_to_end: false
            show:
              in_header: true
              in_chart: false
          - entity: sensor.2115_general_forecast
            name: Predicted Price
            type: area
            color: orange
            extend_to_end: false
            show:
              in_header: false
              in_chart: true
            data_generator: |
              return entity.attributes.forecasts.map((entry) => {
                return [new Date(entry.start_time), entry.per_kwh];
              });
      ### End of Apex Chart Configuration

**Comment by bengAThome** [comment]
Wow. I thought graphana was good...yet another thing to try out :)

**Comment by micarex** [comment]
Thanks for sharing @chiefcomm .  Definitely going to be using Apex Charts more.  Very neat.

**Comment by bengAThome** [comment]
Both the Apex Charts from @chiefcomm and the Amber Electric integration from @madpilot work really well.
I'm using the Dev version of HA with no problems.
I did have to restart HA OS to get the AE integration to show up. (probably because I had the old integration.)
Oh, and if anyone cuts and pastes @chiefcomms excellent code, If you are using the web lovelace gui, you need to remove the first "-"....
So it looks like:
type: custom:apexcharts-card
graph_span: 30h

And, if like me you still have a white background, update the "renewable" display colours :-)

**Comment by bengAThome** [comment]
One odd thing I notice is that the renewables forecast data is stored in the same table as the per/kW forecast data.
So when you mouse over the renewables, the value is correct, but its not displaying it as a %. Really minor issue though.
![image](https://user-images.githubusercontent.com/82250031/125236798-e8915380-e327-11eb-92b2-6440a2fb67c9.png)

**Comment by bjeanes** [comment]
> Based on thresshold values I then run scripts to send MODBUS commands to my Fronius inverter to tell the battery to charge/discharge.

@micarex oh my this is exactly what I want to do in my house which I just bought. It doesn't yet have battery/solar and I've been trying to find out what batteries will let me programmatically charge from grid, discharge to grid, or float to match house demand.

I take it from your comment your Fronius set up works for all that. Are you happy with that option? Did you explore others? I've been surprised how little information there is out there on this!

**Comment by bjeanes** [comment]
> One odd thing I notice is that the renewables forecast data is stored in the same table as the per/kW forecast data.
So when you mouse over the renewables, the value is correct, but its not displaying it as a %. Really minor issue though.

I've got an updated card definition here which fixes that. It also adds a second y-axis for `%` and pins it to `min: 0` and `max: 100`.

![image](https://user-images.githubusercontent.com/2560/125573541-e8ed4573-c395-4e91-be65-147fbc42b66a.png)

```yml
type: custom:apexcharts-card
graph_span: 35h
header:
  show: true
  title: Amber Price 24hrs
  show_states: true
  colorize_states: true
now:
  show: true
  color: red
  label: Now
span:
  start: minute
  offset: '-24h'
apex_config:
  chart:
    type: area
    height: 250
  stroke:
    show: true
    width: 2
    curve: smooth
  legend:
    show: false
  dataLabels:
    enabled: false
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        month: ddd
        day: ddd
  fill:
    type: gradient
    gradient:
      shadeIntensity: 1
      inverseColors: false
      opacityFrom: 0.45
      opacityTo: 0.05
      stops:
        - 20
        - 100
        - 100
        - 100
yaxis:
  - id: price
  - id: renewables_perc
    min: 0
    max: 100
    opposite: true
series:
  - entity: sensor.amber_electric_3056_general_price
    yaxis_id: price
    name: Price
    curve: smooth
    type: area
    color: black
    extend_to_end: false
  - entity: sensor.amber_electric_3056_renewables
    yaxis_id: renewables_perc
    unit: '%'
    name: Renewables in Grid
    curve: smooth
    type: area
    color: green
    extend_to_end: false
    show:
      in_header: true
      in_chart: true
  - entity: sensor.amber_electric_3056_general_forecast
    yaxis_id: renewables_perc
    unit: '%'
    name: Renewables in Grid
    curve: smooth
    type: area
    color: green
    extend_to_end: false
    show:
      in_header: false
      in_chart: true
    data_generator: |
      return entity.attributes.forecasts.map((entry) => {
        return [new Date(entry.nem_date), entry.renewables];
      });
  - entity: sensor.amber_electric_3056_general_forecast
    yaxis_id: price
    name: Predicted Price
    type: area
    color: orange
    extend_to_end: false
    show:
      in_header: true
      in_chart: false
  - entity: sensor.amber_electric_3056_general_forecast
    yaxis_id: price
    name: Predicted Price
    type: area
    color: orange
    extend_to_end: false
    show:
      in_header: false
      in_chart: true
    data_generator: |
      return entity.attributes.forecasts.map((entry) => {
        return [new Date(entry.nem_date), entry.per_kwh];
      });
```

Obviously, replace with your own sensor names.

---

I also have an EAGLE-200 connected, so I have a pretty sick dashboard now:

![image](https://user-images.githubusercontent.com/2560/125573972-5549b9a6-cce2-4da3-944b-9b215e00817b.png)
